# site-wide settings
title: JD's Blog 
description: >- 
  A blog about AI stuff, experiments and experiences.
permalink: /:title/

# Build settings
remote_theme: "jekyll/minima@1e8a445"
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Minima-specific settings (applicable to Minima v3 and above only)
minima:
  skin: classic
  social_links:
    - title: JD's mail
      icon: envelope
      url: "mailto:mathisdittrich@gmail.com"
  hide_site_feed_link: false

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME