# site-wide settings
title: A fynnomenal blog
description: >- 
  A fynnomenal blog about AI stuff, I guess?
permalink: /:title/

# Build settings
remote_theme: "jekyll/minima@1e8a445"
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Minima-specific settings (applicable to Minima v3 and above only)
minima:
  skin: classic
  social_links:
    - title: fynnomenon on discord
      icon: discord
      url: "https://discordapp.com/users/504720288752205827"
    - title: fynnomenon on X
      icon: x-twitter
      url: "https://x.com/fynn_61"
  hide_site_feed_link: false

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME